# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-site
  labels:
    app: fastify-site
    app.kubernetes.io/name: fastify-site
    app.kubernetes.io/component: Fastify
    app.kubernetes.io/version: "4.3.0"
    tier: frontend
  namespace: your-namespace
spec:
  replicas: 1
  # Change this to 3 in production deployment
  revisionHistoryLimit: 1 
  selector:
    matchLabels:
      app: fastify-site
      app.kubernetes.io/name: fastify-site
      tier: frontend
  template:
    metadata:
      labels:
        app: fastify-site
        app.kubernetes.io/name: fastify-site
        app.kubernetes.io/component: WordPress
        app.kubernetes.io/version: "6.0.1"
        tier: frontend
      annotations:
        linkerd.io/inject: disabled
    spec:
      nodeSelector: 
        kubernetes.io/hostname: "your-hostname"
      containers:
        - name: fastify-instance
          image: your-image/your-tag
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: 
            requests:
              cpu: "0.1"
              memory: 128Mi
            limits:
              cpu: "0.5"
              memory: 256Mi
      # imagePullSecrets:
      #   - name: registry-myapp